apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: backend-cert-sync 
  namespace: istio-ingress
spec:
  vault:
    name: akv-aks-certificates # name of key vault
    object:
      name: backend-cert # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: backend-tls # kubernetes secret name
      type: kubernetes.io/tls # kubernetes secret type